# backend/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=asmasync
      - POSTGRES_PASSWORD=asmasync_secret
      - POSTGRES_DB=asmasync_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://asmasync:asmasync_secret@db/asmasync_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changeme_in_prod_secret_key_12345
      - ENVIRONMENT=production
      - CORS_ORIGINS=["http://localhost:4200"]
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
