"""add_date_of_birth_to_user_profiles

Revision ID: 93f01448e6cd
Revises: ade43e7a3fc3
Create Date: 2026-06-02 05:34:50.457478+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f01448e6cd'
down_revision: Union[str, None] = 'ade43e7a3fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_of_birth')
    # ### end Alembic commands ###
