"""add_nurses_table

Revision ID: ade43e7a3fc3
Revises: d6915fe0885d
Create Date: 2026-05-26 06:41:13.832765+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade43e7a3fc3'
down_revision: Union[str, None] = 'd6915fe0885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=100), nullable=True),
    sa.Column('clues', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clues')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_table('hospital_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clues', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clues')
    )
    op.create_index(op.f('ix_hospital_branches_id'), 'hospital_branches', ['id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('next_follow_up', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_table('nurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assisted_doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assisted_doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_nurses_id'), 'nurses', ['id'], unique=False)
    op.create_table('patient_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pef_value', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_viewed_by_doctor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_alerts_id'), 'patient_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_patient_alerts_user_id'), 'patient_alerts', ['user_id'], unique=False)
    op.create_table('doctor_hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['hospital_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_hospitals_id'), 'doctor_hospitals', ['id'], unique=False)
    op.add_column('action_plans', sa.Column('green_zone_instructions', sa.Text(), nullable=True))
    op.add_column('action_plans', sa.Column('yellow_zone_instructions', sa.Text(), nullable=True))
    op.add_column('action_plans', sa.Column('red_zone_instructions', sa.Text(), nullable=True))
    op.add_column('action_plans', sa.Column('emergency_contact', sa.String(length=255), nullable=True))
    op.alter_column('action_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('action_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_unique_constraint(None, 'action_plans', ['user_id'])
    op.add_column('action_steps', sa.Column('zone', sa.String(length=10), nullable=True))
    op.alter_column('action_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_action_steps_id'), 'action_steps', ['id'], unique=False)
    op.alter_column('app_settings', 'reminder_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'daily'::character varying"))
    op.alter_column('app_settings', 'theme',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('app_settings', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('app_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.alter_column('appointments', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_appointments_doc'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_pat'), table_name='appointments')
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.add_column('clinical_profiles', sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('clinical_profiles', sa.Column('personal_best_pef', sa.Integer(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('clinical_profiles', sa.Column('asthma_type', sa.String(length=50), nullable=True))
    op.add_column('clinical_profiles', sa.Column('diagnosis_date', sa.DATE(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('known_allergies', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('family_history_mother', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('family_history_father', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('family_history_siblings', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('family_history_grandparents', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('smoking', sa.String(length=100), nullable=True))
    op.add_column('clinical_profiles', sa.Column('alcohol', sa.String(length=100), nullable=True))
    op.add_column('clinical_profiles', sa.Column('exercise', sa.String(length=100), nullable=True))
    op.add_column('clinical_profiles', sa.Column('diet', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('surgeries_traumas', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('photo_url', sa.Text(), nullable=True))
    op.add_column('clinical_profiles', sa.Column('spirometer_id', sa.String(length=100), nullable=True))
    op.add_column('clinical_profiles', sa.Column('inhaler_id', sa.String(length=100), nullable=True))
    op.add_column('clinical_profiles', sa.Column('verified_by_doctor_id', sa.Integer(), nullable=True))
    op.alter_column('clinical_profiles', 'blood_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('clinical_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clinical_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_clinical_profiles_id'), 'clinical_profiles', ['id'], unique=False)
    op.create_foreign_key(None, 'clinical_profiles', 'users', ['verified_by_doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('clinical_profiles', 'family_history')
    op.drop_column('clinical_profiles', 'chronic_conditions')
    op.drop_column('clinical_profiles', 'past_surgeries')
    op.drop_column('clinical_profiles', 'vaccination_status')
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('devices', 'device_mac_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=17),
               existing_nullable=True)
    op.alter_column('devices', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.alter_column('doctor_patients', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('doctor_patients_doctor_id_patient_id_key'), 'doctor_patients', type_='unique')
    op.drop_index(op.f('idx_doctor_patients_doc'), table_name='doctor_patients')
    op.drop_index(op.f('idx_doctor_patients_pat'), table_name='doctor_patients')
    op.create_index(op.f('ix_doctor_patients_id'), 'doctor_patients', ['id'], unique=False)
    op.create_unique_constraint('uq_doctor_patient', 'doctor_patients', ['doctor_id', 'patient_id'])
    op.alter_column('doctors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('doctors_doctor_code_key'), 'doctors', type_='unique')
    op.drop_index(op.f('idx_doctors_code'), table_name='doctors')
    op.create_index(op.f('ix_doctors_doctor_code'), 'doctors', ['doctor_code'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.alter_column('emergency_contacts', 'contact_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('emergency_contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('emergency_contacts', 'relationship',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('emergency_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emergency_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.alter_column('manual_entries', 'measured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=False)
    op.alter_column('manual_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_manual_entries_id'), 'manual_entries', ['id'], unique=False)
    op.add_column('notifications', sa.Column('prediction_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'predictions', ['prediction_id'], ['id'], ondelete='SET NULL')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'created_at')
    op.add_column('predictions', sa.Column('probability', sa.DECIMAL(precision=5, scale=4), nullable=True))
    op.add_column('predictions', sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('predictions', sa.Column('predicted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('predictions', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.alter_column('predictions', 'risk_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_index(op.f('idx_predictions_user'), table_name='predictions')
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.drop_constraint(op.f('predictions_reading_id_fkey'), 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'confidence_score')
    op.drop_column('predictions', 'created_at')
    op.drop_column('predictions', 'reading_id')
    op.drop_column('predictions', 'prediction_details')
    op.add_column('spirometer_readings', sa.Column('symptom_intensity', sa.VARCHAR(length=20), nullable=True))
    op.add_column('spirometer_readings', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('aqi', sa.Integer(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('temperature', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('spirometer_readings', sa.Column('humidity', sa.Integer(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('pollen_level', sa.TEXT(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('location_name', sa.TEXT(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('spo2', sa.Integer(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('heart_rate', sa.Integer(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('spirometer_readings', sa.Column('sleep_hours', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('spirometer_readings', sa.Column('respiratory_rate', sa.Integer(), nullable=True))
    op.alter_column('spirometer_readings', 'pef',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('spirometer_readings', 'measured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('spirometer_readings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_spirometer_date'), table_name='spirometer_readings')
    op.drop_index(op.f('idx_spirometer_user'), table_name='spirometer_readings')
    op.create_index(op.f('ix_spirometer_readings_id'), 'spirometer_readings', ['id'], unique=False)
    op.drop_column('spirometer_readings', 'fev1_fvc_ratio')
    op.drop_column('spirometer_readings', 'pef_zone')
    op.drop_column('spirometer_readings', 'fvc')
    op.drop_column('spirometer_readings', 'context')
    op.add_column('user_profiles', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('address_street', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('address_state', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('address_zip', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('health_insurance_number', sa.String(length=100), nullable=True))
    op.alter_column('user_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.drop_column('user_profiles', 'height_cm')
    op.drop_column('user_profiles', 'smoking_status')
    op.drop_column('user_profiles', 'emergency_number')
    op.drop_column('user_profiles', 'diagnosis_date')
    op.drop_column('user_profiles', 'weight_kg')
    op.drop_column('user_profiles', 'known_triggers')
    op.drop_column('user_profiles', 'dob')
    op.drop_column('user_profiles', 'primary_physician')
    op.drop_column('user_profiles', 'allergies')
    op.drop_column('user_profiles', 'asthma_severity')
    op.add_column('users', sa.Column('avatar_background_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'supabase_uid',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'patient'::character varying"))
    op.alter_column('users', 'avatar_seed',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'avatar_background',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_supabase_uid'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_supabase_uid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.drop_column('users', 'last_login')
    op.add_column('vital_signs', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('vital_signs', sa.Column('spo2', sa.Integer(), nullable=True))
    op.add_column('vital_signs', sa.Column('sleep_hours', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('vital_signs', sa.Column('measured_at', sa.TIMESTAMP(), nullable=False))
    op.alter_column('vital_signs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_vital_signs_id'), 'vital_signs', ['id'], unique=False)
    op.create_foreign_key(None, 'vital_signs', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vital_signs', 'body_temperature')
    op.drop_column('vital_signs', 'recorded_at')
    op.drop_column('vital_signs', 'respiratory_rate')
    op.drop_column('vital_signs', 'oxygen_saturation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('oxygen_saturation', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('respiratory_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('body_temperature', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vital_signs', type_='foreignkey')
    op.drop_index(op.f('ix_vital_signs_id'), table_name='vital_signs')
    op.alter_column('vital_signs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('vital_signs', 'measured_at')
    op.drop_column('vital_signs', 'sleep_hours')
    op.drop_column('vital_signs', 'spo2')
    op.drop_column('vital_signs', 'device_id')
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_supabase_uid_key'), 'users', ['supabase_uid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_supabase_uid'), 'users', ['supabase_uid'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'avatar_background',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'avatar_seed',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'patient'::character varying"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'supabase_uid',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'avatar_background_type')
    op.add_column('user_profiles', sa.Column('asthma_severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('primary_physician', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('known_triggers', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('weight_kg', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('diagnosis_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('emergency_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('smoking_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('height_cm', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.alter_column('user_profiles', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_profiles', 'health_insurance_number')
    op.drop_column('user_profiles', 'address_zip')
    op.drop_column('user_profiles', 'address_state')
    op.drop_column('user_profiles', 'address_city')
    op.drop_column('user_profiles', 'address_street')
    op.drop_column('user_profiles', 'phone_number')
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.add_column('spirometer_readings', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('spirometer_readings', sa.Column('fvc', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('spirometer_readings', sa.Column('pef_zone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('spirometer_readings', sa.Column('fev1_fvc_ratio', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_spirometer_readings_id'), table_name='spirometer_readings')
    op.create_index(op.f('idx_spirometer_user'), 'spirometer_readings', ['user_id'], unique=False)
    op.create_index(op.f('idx_spirometer_date'), 'spirometer_readings', ['measured_at'], unique=False)
    op.alter_column('spirometer_readings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('spirometer_readings', 'measured_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('spirometer_readings', 'pef',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.drop_column('spirometer_readings', 'respiratory_rate')
    op.drop_column('spirometer_readings', 'sleep_hours')
    op.drop_column('spirometer_readings', 'steps')
    op.drop_column('spirometer_readings', 'heart_rate')
    op.drop_column('spirometer_readings', 'spo2')
    op.drop_column('spirometer_readings', 'location_name')
    op.drop_column('spirometer_readings', 'pollen_level')
    op.drop_column('spirometer_readings', 'humidity')
    op.drop_column('spirometer_readings', 'temperature')
    op.drop_column('spirometer_readings', 'aqi')
    op.drop_column('spirometer_readings', 'notes')
    op.drop_column('spirometer_readings', 'symptom_intensity')
    op.add_column('predictions', sa.Column('prediction_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('reading_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('confidence_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('predictions_reading_id_fkey'), 'predictions', 'spirometer_readings', ['reading_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.create_index(op.f('idx_predictions_user'), 'predictions', ['user_id'], unique=False)
    op.alter_column('predictions', 'risk_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('predictions', 'model_version')
    op.drop_column('predictions', 'predicted_at')
    op.drop_column('predictions', 'input_data')
    op.drop_column('predictions', 'probability')
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'sent_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'prediction_id')
    op.drop_index(op.f('ix_manual_entries_id'), table_name='manual_entries')
    op.alter_column('manual_entries', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('manual_entries', 'measured_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.alter_column('emergency_contacts', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emergency_contacts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emergency_contacts', 'relationship',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('emergency_contacts', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('emergency_contacts', 'contact_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_code'), table_name='doctors')
    op.create_index(op.f('idx_doctors_code'), 'doctors', ['doctor_code'], unique=False)
    op.create_unique_constraint(op.f('doctors_doctor_code_key'), 'doctors', ['doctor_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctors', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_doctor_patient', 'doctor_patients', type_='unique')
    op.drop_index(op.f('ix_doctor_patients_id'), table_name='doctor_patients')
    op.create_index(op.f('idx_doctor_patients_pat'), 'doctor_patients', ['patient_id'], unique=False)
    op.create_index(op.f('idx_doctor_patients_doc'), 'doctor_patients', ['doctor_id'], unique=False)
    op.create_unique_constraint(op.f('doctor_patients_doctor_id_patient_id_key'), 'doctor_patients', ['doctor_id', 'patient_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctor_patients', 'assigned_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.alter_column('devices', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'last_sync_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('devices', 'device_mac_address',
               existing_type=sa.String(length=17),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('devices', 'device_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('clinical_profiles', sa.Column('vaccination_status', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_profiles', sa.Column('past_surgeries', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_profiles', sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clinical_profiles', sa.Column('family_history', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clinical_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_clinical_profiles_id'), table_name='clinical_profiles')
    op.alter_column('clinical_profiles', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clinical_profiles', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clinical_profiles', 'blood_type',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('clinical_profiles', 'verified_by_doctor_id')
    op.drop_column('clinical_profiles', 'inhaler_id')
    op.drop_column('clinical_profiles', 'spirometer_id')
    op.drop_column('clinical_profiles', 'photo_url')
    op.drop_column('clinical_profiles', 'surgeries_traumas')
    op.drop_column('clinical_profiles', 'diet')
    op.drop_column('clinical_profiles', 'exercise')
    op.drop_column('clinical_profiles', 'alcohol')
    op.drop_column('clinical_profiles', 'smoking')
    op.drop_column('clinical_profiles', 'family_history_grandparents')
    op.drop_column('clinical_profiles', 'family_history_siblings')
    op.drop_column('clinical_profiles', 'family_history_father')
    op.drop_column('clinical_profiles', 'family_history_mother')
    op.drop_column('clinical_profiles', 'known_allergies')
    op.drop_column('clinical_profiles', 'diagnosis_date')
    op.drop_column('clinical_profiles', 'asthma_type')
    op.drop_column('clinical_profiles', 'weight_kg')
    op.drop_column('clinical_profiles', 'personal_best_pef')
    op.drop_column('clinical_profiles', 'height_cm')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.create_index(op.f('idx_appointments_pat'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('idx_appointments_doc'), 'appointments', ['doctor_id'], unique=False)
    op.alter_column('appointments', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.alter_column('app_settings', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_settings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_settings', 'language',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('app_settings', 'theme',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('app_settings', 'reminder_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'daily'::character varying"))
    op.drop_index(op.f('ix_action_steps_id'), table_name='action_steps')
    op.alter_column('action_steps', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('action_steps', 'zone')
    op.drop_constraint(None, 'action_plans', type_='unique')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.alter_column('action_plans', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_plans', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('action_plans', 'emergency_contact')
    op.drop_column('action_plans', 'red_zone_instructions')
    op.drop_column('action_plans', 'yellow_zone_instructions')
    op.drop_column('action_plans', 'green_zone_instructions')
    op.drop_index(op.f('ix_doctor_hospitals_id'), table_name='doctor_hospitals')
    op.drop_table('doctor_hospitals')
    op.drop_index(op.f('ix_patient_alerts_user_id'), table_name='patient_alerts')
    op.drop_index(op.f('ix_patient_alerts_id'), table_name='patient_alerts')
    op.drop_table('patient_alerts')
    op.drop_index(op.f('ix_nurses_id'), table_name='nurses')
    op.drop_table('nurses')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_hospital_branches_id'), table_name='hospital_branches')
    op.drop_table('hospital_branches')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
