"""Add doctor_code clean

Revision ID: bbaa0638c238
Revises: 2ac6cbdcfb5c
Create Date: 2026-02-18 02:01:27.274189+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbaa0638c238'
down_revision: Union[str, None] = '2ac6cbdcfb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asthma_type', sa.String(), nullable=True),
    sa.Column('personal_best_pef', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('sys_bp', sa.Integer(), nullable=True),
    sa.Column('dia_bp', sa.Integer(), nullable=True),
    sa.Column('activity_context', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_vitals_date', 'vital_signs', ['user_id', 'measured_at'], unique=False)
    op.create_index(op.f('ix_vital_signs_id'), 'vital_signs', ['id'], unique=False)
    op.create_index(op.f('ix_vital_signs_measured_at'), 'vital_signs', ['measured_at'], unique=False)
    op.create_table('doctor_patients',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'patient_id')
    )
    op.drop_table('action_steps')
    op.drop_table('predictions')
    op.drop_table('emergency_contacts')
    op.drop_table('app_settings')
    op.drop_table('manual_entries')
    op.drop_table('spirometer_readings')
    op.drop_table('action_plans')
    op.drop_table('environmental_risk_thresholds')
    op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('date_of_birth', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('asthma_type', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_relation', sa.String(), nullable=True))
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('doctor_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doctor_code')
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('patients', 'emergency_contact_relation')
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'asthma_type')
    op.drop_column('patients', 'weight_kg')
    op.drop_column('patients', 'height_cm')
    op.drop_column('patients', 'location_city')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'phone')
    op.create_table('environmental_risk_thresholds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pm25_max', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('co2_max', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('humidity_max', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_min', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_max', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('environmental_risk_thresholds_pkey'))
    )
    op.create_table('action_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=255), server_default=sa.text("'Plan de Emergencia'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('action_plans_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('action_plans_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spirometer_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pef', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fev1', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('measured_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('fev1 > 0::numeric', name=op.f('spirometer_readings_fev1_check')),
    sa.CheckConstraint('pef > 0', name=op.f('spirometer_readings_pef_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('spirometer_readings_pkey'))
    )
    op.create_table('manual_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manual_pef', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('measured_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('manual_pef > 0', name=op.f('manual_entries_manual_pef_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_entries_pkey'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('reminder_frequency', sa.VARCHAR(length=20), server_default=sa.text("'daily'::character varying"), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'light'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), server_default=sa.text("'es'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('app_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('emergency_contacts_pkey'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('probability', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('predicted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('probability >= 0::numeric AND probability <= 1::numeric', name=op.f('predictions_probability_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.create_table('action_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('step_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_critical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], name=op.f('action_steps_action_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('action_steps_pkey'))
    )
    op.drop_table('doctor_patients')
    op.drop_index(op.f('ix_vital_signs_measured_at'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_id'), table_name='vital_signs')
    op.drop_index('idx_user_vitals_date', table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
