"""expand_gender_column

Revision ID: d9662e58c0a8
Revises: d07c023e49b7
Create Date: 2026-03-13 00:56:51.753241+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9662e58c0a8'
down_revision: Union[str, None] = 'd07c023e49b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurements', 'fev1',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('measurements', 'sleep_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('measurements', 'symptoms',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('patients', 'current_medications',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'known_allergies_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'known_allergies_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'current_medications',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('measurements', 'symptoms',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('measurements', 'sleep_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('measurements', 'fev1',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
